### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by anthony-paikai** [anthony-paikai/FCC-Leaderboard#1]
Update Readme.md

**Comment by IMPrimph** [comment]
@anthony-paikai 
Can you explain the project briefly, I will write the readme file

**Comment by anthony-paikai** [comment]
Hi @IMPrimph . This was an old project from freecodecamp. After some research, I have learned that it is deprecated and that the API endpoints no longer work. If you could add a message to the bottom of the readme that says such, I will go ahead and merge and close this issue.

**Comment by IMPrimph** [comment]
@anthony-paikai Got it, will do that
